name: Generate release notes HTML
description: Generate HTML release notes for inclusion in build artifacts

inputs:
  output_path:
    description: Path for the output HTML file
    required: true

  github_token:
    description: GitHub token for API access
    required: true

  git_hash:
    description: Git commit hash to include in the HTML
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install markdown2
      shell: bash
      run: pip3 install markdown2 requests

    - name: Query pull requests
      shell: bash
      env:
        GITHUB_ACCESS_TOKEN: ${{ inputs.github_token }}
      run: |
        ./scripts/tools/release-notes-drafter.py \
            query \
            --start_time            $RELEASE_START_TIME \
            --out_pull_requests_csv pull-requests.csv

    - name: Generate HTML release notes
      shell: bash
      env:
        GITHUB_ACCESS_TOKEN: ${{ inputs.github_token }}
      run: |
        mkdir -p "$(dirname "${{ inputs.output_path }}")"

        ./scripts/tools/release-notes-drafter.py \
            process \
            --input_csv_file   pull-requests.csv \
            --html_version_tag $DOSBOX_VERSION_AND_HASH \
            --out_html_file    "${{ inputs.output_path }}"
