version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "@dosbox-staging/maintenance-team"
    labels:
      - "CI"
