/*
 *  Copyright (C) 2022       The DOSBox Staging Team
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#include "cp.h"
#include "checks.h"

CHECK_NARROWING();

// This is a 'fallback' code page, to be used when current one is unable
// to find matching character for the given UTF-8 code point


// TODO: add fallbacks fo remaining characters, see:
// - https://en.wikipedia.org/wiki/List_of_Unicode_characters

// Use this if there is no reasonable ASCII-7 replacement
#define NNN unknown_character

const CodePageMapping cp_ascii = {
    { 0x00a0, ' ' },  // NO-BREAK SPACE
    { 0x00a1, '!' },  // INVERTED EXCLAMATION MARK
    { 0x00a2, 'c' },  // CENT SIGN
    { 0x00a3, 'L' },  // POUND SIGN
    { 0x00a4, '$' },  // CURRENCY SIGN
    { 0x00a5, 'Y' },  // YEN SIGN
    { 0x00a6, '|' },  // BROKEN VERTICAL BAR
    { 0x00a7, '#' },  // SECTION SIGN
    { 0x00a8, '"' },  // DIAERESIS
    { 0x00a9, 'C' },  // COPYRIGHT SIGN
    { 0x00aa, NNN },  // FEMININE ORDINAL INDICATOR
    { 0x00ab, '<' },  // LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
    { 0x00ac, '~' },  // NOT SIGN
    { 0x00ad, '-' },  // SOFT HYPHEN
    { 0x00ae, NNN },  // REGISTERED SIGN
    { 0x00af, NNN },  // MACRON
    { 0x00b0, NNN },  // DEGREE SIGN
    { 0x00b1, NNN },  // PLUS-MINUS SIGN
    { 0x00b2, NNN },  // SUPERSCRIPT TWO
    { 0x00b3, NNN },  // SUPERSCRIPT THREE
    { 0x00b4, '\'' }, // ACUTE ACCENT
    { 0x00b5, 'u' },  // MICRO SIGN
    { 0x00b6, NNN },  // PILCROW SIGN
    { 0x00b7, NNN },  // MIDDLE DOT
    { 0x00b8, ',' },  // CEDILLA
    { 0x00b9, NNN },  // SUPERSCRIPT ONE
    { 0x00ba, NNN },  // MASCULINE ORDINAL INDICATOR
    { 0x00bb, '>' },  // RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
    { 0x00bc, NNN },  // VULGAR FRACTION ONE QUARTER
    { 0x00bd, NNN },  // VULGAR FRACTION ONE HALF
    { 0x00be, NNN },  // VULGAR FRACTION THREE QUARTERS
    { 0x00bf, '?' },  // INVERTED QUESTION MARK

    // For Latin script alphabets, we can find sane 7-bit ASCII
	// fallbacks for almost every glyph.
    { 0x00c0, 'A' },  // LATIN CAPITAL LETTER A WITH GRAVE
    { 0x00c1, 'A' },  // LATIN CAPITAL LETTER A WITH ACUTE
    { 0x00c2, 'A' },  // LATIN CAPITAL LETTER A WITH CIRCUMFLEX
    { 0x00c3, 'A' },  // LATIN CAPITAL LETTER A WITH TILDE
    { 0x00c4, 'A' },  // LATIN CAPITAL LETTER A WITH DIAERESIS
    { 0x00c5, 'A' },  // LATIN CAPITAL LETTER A WITH RING ABOVE
    { 0x00c6, 'A' },  // LATIN CAPITAL LIGATURE AE
    { 0x00c7, 'C' },  // LATIN CAPITAL LETTER C WITH CEDILLA
    { 0x00c8, 'E' },  // LATIN CAPITAL LETTER E WITH GRAVE
    { 0x00c9, 'E' },  // LATIN CAPITAL LETTER E WITH ACUTE
    { 0x00ca, 'E' },  // LATIN CAPITAL LETTER E WITH CIRCUMFLEX
    { 0x00cb, 'E' },  // LATIN CAPITAL LETTER E WITH DIAERESIS
    { 0x00cc, 'I' },  // LATIN CAPITAL LETTER I WITH GRAVE
    { 0x00cd, 'I' },  // LATIN CAPITAL LETTER I WITH ACUTE
    { 0x00ce, 'I' },  // LATIN CAPITAL LETTER I WITH CIRCUMFLEX
    { 0x00cf, 'I' },  // LATIN CAPITAL LETTER I WITH DIAERESIS
    { 0x00d0, ':' },  // LATIN CAPITAL LETTER ETH
    { 0x00d1, 'N' },  // LATIN CAPITAL LETTER N WITH TILDE
    { 0x00d2, 'O' },  // LATIN CAPITAL LETTER O WITH GRAVE
    { 0x00d3, 'O' },  // LATIN CAPITAL LETTER O WITH ACUTE
    { 0x00d4, 'O' },  // LATIN CAPITAL LETTER O WITH CIRCUMFLEX
    { 0x00d5, 'O' },  // LATIN CAPITAL LETTER O WITH TILDE
    { 0x00d6, 'O' },  // LATIN CAPITAL LETTER O WITH DIAERESIS
    { 0x00d7, '*' },  // MULTIPLICATION SIGN
    { 0x00d8, 'O' },  // LATIN CAPITAL LETTER O WITH STROKE
    { 0x00d9, 'U' },  // LATIN CAPITAL LETTER U WITH GRAVE
    { 0x00da, 'U' },  // LATIN CAPITAL LETTER U WITH ACUTE
    { 0x00db, 'U' },  // LATIN CAPITAL LETTER U WITH CIRCUMFLEX
    { 0x00dc, 'U' },  // LATIN CAPITAL LETTER U WITH DIAERESIS
    { 0x00dd, 'Y' },  // LATIN CAPITAL LETTER Y WITH ACUTE
    { 0x00de, NNN },  // LATIN CAPITAL LETTER THORN
    { 0x00df, NNN },  // LATIN SMALL LETTER SHARP S
    { 0x00e0, 'a' },  // LATIN SMALL LETTER A WITH GRAVE
    { 0x00e1, 'a' },  // LATIN SMALL LETTER A WITH ACUTE
    { 0x00e2, 'a' },  // LATIN SMALL LETTER A WITH CIRCUMFLEX
    { 0x00e3, 'a' },  // LATIN SMALL LETTER A WITH TILDE
    { 0x00e4, 'a' },  // LATIN SMALL LETTER A WITH DIAERESIS
    { 0x00e5, 'a' },  // LATIN SMALL LETTER A WITH RING ABOVE
    { 0x00e6, 'a' },  // LATIN SMALL LIGATURE AE
    { 0x00e7, 'c' },  // LATIN SMALL LETTER C WITH CEDILLA
    { 0x00e8, 'e' },  // LATIN SMALL LETTER E WITH GRAVE
    { 0x00e9, 'e' },  // LATIN SMALL LETTER E WITH ACUTE
    { 0x00ea, 'e' },  // LATIN SMALL LETTER E WITH CIRCUMFLEX
    { 0x00eb, 'e' },  // LATIN SMALL LETTER E WITH DIAERESIS
    { 0x00ec, 'i' },  // LATIN SMALL LETTER I WITH GRAVE
    { 0x00ed, 'i' },  // LATIN SMALL LETTER I WITH ACUTE
    { 0x00ee, 'i' },  // LATIN SMALL LETTER I WITH CIRCUMFLEX
    { 0x00ef, 'i' },  // LATIN SMALL LETTER I WITH DIAERESIS
    { 0x00f0, NNN },  // LATIN SMALL LETTER ETH
    { 0x00f1, 'n' },  // LATIN SMALL LETTER N WITH TILDE
    { 0x00f2, 'o' },  // LATIN SMALL LETTER O WITH GRAVE
    { 0x00f3, 'o' },  // LATIN SMALL LETTER O WITH ACUTE
    { 0x00f4, 'o' },  // LATIN SMALL LETTER O WITH CIRCUMFLEX
    { 0x00f5, 'o' },  // LATIN SMALL LETTER O WITH TILDE
    { 0x00f6, 'o' },  // LATIN SMALL LETTER O WITH DIAERESIS
    { 0x00f7, '/' },  // DIVISION SIGN
    { 0x00f8, 'o' },  // LATIN SMALL LETTER O WITH STROKE
    { 0x00f9, 'u' },  // LATIN SMALL LETTER U WITH GRAVE
    { 0x00fa, 'u' },  // LATIN SMALL LETTER U WITH ACUTE
    { 0x00fb, 'u' },  // LATIN SMALL LETTER U WITH CIRCUMFLEX
    { 0x00fc, 'u' },  // LATIN SMALL LETTER U WITH DIAERESIS
    { 0x00fd, 'y' },  // LATIN SMALL LETTER Y WITH ACUTE
    { 0x00fe, '_' },  // LATIN SMALL LETTER THORN
    { 0x00ff, 'y' },  // LATIN SMALL LETTER Y WITH DIAERESIS
    { 0x0100, 'A' },  // LATIN CAPITAL LETTER A WITH MACRON
    { 0x0101, 'a' },  // LATIN SMALL LETTER A WITH MACRON
    { 0x0102, 'A' },  // LATIN CAPITAL LETTER A WITH BREVE
    { 0x0103, 'a' },  // LATIN SMALL LETTER A WITH BREVE
    { 0x0104, 'A' },  // LATIN CAPITAL LETTER A WITH OGONEK
    { 0x0105, 'a' },  // LATIN SMALL LETTER A WITH OGONEK
    { 0x0106, 'C' },  // LATIN CAPITAL LETTER C WITH ACUTE
    { 0x0107, 'c' },  // LATIN SMALL LETTER C WITH ACUTE
    { 0x010c, 'C' },  // LATIN CAPITAL LETTER C WITH CARON
    { 0x010d, 'c' },  // LATIN SMALL LETTER C WITH CARON
    { 0x010e, 'D' },  // LATIN CAPITAL LETTER D WITH CARON
    { 0x010f, 'd' },  // LATIN SMALL LETTER D WITH CARON
    { 0x0110, 'D' },  // LATIN CAPITAL LETTER D WITH STROKE
    { 0x0111, 'd' },  // LATIN SMALL LETTER D WITH STROKE
    { 0x0112, 'E' },  // LATIN CAPITAL LETTER E WITH MACRON
    { 0x0113, 'e' },  // LATIN SMALL LETTER E WITH MACRON
    { 0x0116, 'E' },  // LATIN CAPITAL LETTER E WITH DOT ABOVE
    { 0x0117, 'e' },  // LATIN SMALL LETTER E WITH DOT ABOVE
    { 0x0118, 'E' },  // LATIN CAPITAL LETTER E WITH OGONEK
    { 0x0119, 'e' },  // LATIN SMALL LETTER E WITH OGONEK
    { 0x011a, 'E' },  // LATIN CAPITAL LETTER E WITH CARON
    { 0x011b, 'e' },  // LATIN SMALL LETTER E WITH CARON
    { 0x011e, 'G' },  // LATIN CAPITAL LETTER G WITH BREVE
    { 0x011f, 'g' },  // LATIN SMALL LETTER G WITH BREVE
    { 0x0122, 'G' },  // LATIN CAPITAL LETTER G WITH CEDILLA
    { 0x0123, 'g' },  // LATIN SMALL LETTER G WITH CEDILLA
    { 0x012a, 'I' },  // LATIN CAPITAL LETTER I WITH MACRON
    { 0x012b, 'i' },  // LATIN SMALL LETTER I WITH MACRON
    { 0x012e, 'I' },  // LATIN CAPITAL LETTER I WITH OGONEK
    { 0x012f, 'i' },  // LATIN SMALL LETTER I WITH OGONEK
    { 0x0130, 'I' },  // LATIN CAPITAL LETTER I WITH DOT ABOVE
    { 0x0131, 'i' },  // LATIN SMALL LETTER DOTLESS I
    { 0x0136, 'K' },  // LATIN CAPITAL LETTER K WITH CEDILLA
    { 0x0137, 'k' },  // LATIN SMALL LETTER K WITH CEDILLA
    { 0x0139, 'L' },  // LATIN CAPITAL LETTER L WITH ACUTE
    { 0x013a, 'l' },  // LATIN SMALL LETTER L WITH ACUTE
    { 0x013b, 'L' },  // LATIN CAPITAL LETTER L WITH CEDILLA
    { 0x013c, 'l' },  // LATIN SMALL LETTER L WITH CEDILLA
    { 0x013d, 'L' },  // LATIN CAPITAL LETTER L WITH CARON
    { 0x013e, 'l' },  // LATIN SMALL LETTER L WITH CARON
    { 0x0141, 'L' },  // LATIN CAPITAL LETTER L WITH STROKE
    { 0x0142, 'l' },  // LATIN SMALL LETTER L WITH STROKE
    { 0x0143, 'N' },  // LATIN CAPITAL LETTER N WITH ACUTE
    { 0x0144, 'n' },  // LATIN SMALL LETTER N WITH ACUTE
    { 0x0145, 'N' },  // LATIN CAPITAL LETTER N WITH CEDILLA
    { 0x0146, 'n' },  // LATIN SMALL LETTER N WITH CEDILLA
    { 0x0147, 'N' },  // LATIN CAPITAL LETTER N WITH CARON
    { 0x0148, 'n' },  // LATIN SMALL LETTER N WITH CARON
    { 0x014c, 'O' },  // LATIN CAPITAL LETTER O WITH MACRON
    { 0x014d, 'o' },  // LATIN SMALL LETTER O WITH MACRON
    { 0x0150, 'O' },  // LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
    { 0x0151, 'o' },  // LATIN SMALL LETTER O WITH DOUBLE ACUTE
    { 0x0154, 'R' },  // LATIN CAPITAL LETTER R WITH ACUTE
    { 0x0155, 'r' },  // LATIN SMALL LETTER R WITH ACUTE
    { 0x0156, 'R' },  // LATIN CAPITAL LETTER R WITH CEDILLA
    { 0x0157, 'r' },  // LATIN SMALL LETTER R WITH CEDILLA
    { 0x0158, 'R' },  // LATIN CAPITAL LETTER R WITH CARON
    { 0x0159, 'r' },  // LATIN SMALL LETTER R WITH CARON
    { 0x015a, 'S' },  // LATIN CAPITAL LETTER S WITH ACUTE
    { 0x015b, 's' },  // LATIN SMALL LETTER S WITH ACUTE
    { 0x015e, 'S' },  // LATIN CAPITAL LETTER S WITH CEDILLA
    { 0x015f, 's' },  // LATIN SMALL LETTER S WITH CEDILLA
    { 0x0160, 'S' },  // LATIN CAPITAL LETTER S WITH CARON
    { 0x0161, 's' },  // LATIN SMALL LETTER S WITH CARON
    { 0x0162, 'T' },  // LATIN CAPITAL LETTER T WITH CEDILLA
    { 0x0163, 't' },  // LATIN SMALL LETTER T WITH CEDILLA
    { 0x0164, 'T' },  // LATIN CAPITAL LETTER T WITH CARON
    { 0x0165, 't' },  // LATIN SMALL LETTER T WITH CARON
    { 0x016a, 'U' },  // LATIN CAPITAL LETTER U WITH MACRON
    { 0x016b, 'u' },  // LATIN SMALL LETTER U WITH MACRON
    { 0x016e, 'U' },  // LATIN CAPITAL LETTER U WITH RING ABOVE
    { 0x016f, 'u' },  // LATIN SMALL LETTER U WITH RING ABOVE
    { 0x0170, 'U' },  // LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
    { 0x0171, 'u' },  // LATIN SMALL LETTER U WITH DOUBLE ACUTE
    { 0x0172, 'U' },  // LATIN CAPITAL LETTER U WITH OGONEK
    { 0x0173, 'u' },  // LATIN SMALL LETTER U WITH OGONEK
    { 0x0179, 'Z' },  // LATIN CAPITAL LETTER Z WITH ACUTE
    { 0x017a, 'z' },  // LATIN SMALL LETTER Z WITH ACUTE
    { 0x017b, 'Z' },  // LATIN CAPITAL LETTER Z WITH DOT ABOVE
    { 0x017c, 'z' },  // LATIN SMALL LETTER Z WITH DOT ABOVE
    { 0x017d, 'Z' },  // LATIN CAPITAL LETTER Z WITH CARON
    { 0x017e, 'z' },  // LATIN SMALL LETTER Z WITH CARON
    { 0x0192, 'f' },  // LATIN SMALL LETTER F WITH HOOK
    { 0x01b5, 'Z' },  // LATIN CAPITAL LETTER Z WITH STROKE 
    { 0x01b6, 'z' },  // LATIN SMALL LETTER Z WITH STROKE 
    { 0x0218, 'S' },  // LATIN CAPITAL LETTER S WITH COMMA BELOW
    { 0x0219, 's' },  // LATIN SMALL LETTER S WITH COMMA BELOW
    { 0x021a, 'T' },  // LATIN CAPITAL LETTER T WITH COMMA BELOW
    { 0x021b, 't' },  // LATIN SMALL LETTER T WITH COMMA BELOW

    { 0x02c7, '^' },  // CARON
    { 0x02d8, '^' },  // BREVE
    { 0x02d9, '\'' }, // DOT ABOVE
    { 0x02db, ',' },  // OGONEK
    { 0x02dd, '"' },  // DOUBLE ACUTE ACCENT

    // Greek alphabet cannot be easily mapped to 7-bit ASCII,
	// but for many glyphs a sane fallback is feasible.
    { 0x0384, '\'' }, // GREEK TONOS
    { 0x0385, '\'' }, // GREEK DIALYTIKA TONOS
    { 0x0386, 'A' },  // GREEK CAPITAL LETTER ALPHA WITH TONOS
    { 0x0388, 'E' },  // GREEK CAPITAL LETTER EPSILON WITH TONOS
    { 0x0389, 'H' },  // GREEK CAPITAL LETTER ETA WITH TONOS
    { 0x038a, 'I' },  // GREEK CAPITAL LETTER IOTA WITH TONOS
    { 0x038c, 'O' },  // GREEK CAPITAL LETTER OMICRON WITH TONOS
    { 0x038e, 'Y' },  // GREEK CAPITAL LETTER UPSILON WITH TONOS
    { 0x038f, NNN },  // GREEK CAPITAL LETTER OMEGA WITH TONOS
    { 0x0390, 'i' },  // GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
    { 0x0391, 'A' },  // GREEK CAPITAL LETTER ALPHA
    { 0x0392, 'B' },  // GREEK CAPITAL LETTER BETA
    { 0x0393, NNN },  // GREEK CAPITAL LETTER GAMMA
    { 0x0394, NNN },  // GREEK CAPITAL LETTER DELTA
    { 0x0395, 'E' },  // GREEK CAPITAL LETTER EPSILON
    { 0x0396, 'Z' },  // GREEK CAPITAL LETTER ZETA
    { 0x0397, 'H' },  // GREEK CAPITAL LETTER ETA
    { 0x0398, NNN },  // GREEK CAPITAL LETTER THETA
    { 0x0399, 'I' },  // GREEK CAPITAL LETTER IOTA
    { 0x039a, 'K' },  // GREEK CAPITAL LETTER KAPPA
    { 0x039b, NNN },  // GREEK CAPITAL LETTER LAMDA
    { 0x039c, 'M' },  // GREEK CAPITAL LETTER MU
    { 0x039d, 'N' },  // GREEK CAPITAL LETTER NU
    { 0x039e, NNN },  // GREEK CAPITAL LETTER XI
    { 0x039f, 'O' },  // GREEK CAPITAL LETTER OMICRON
    { 0x03a0, NNN },  // GREEK CAPITAL LETTER PI
    { 0x03a1, 'P' },  // GREEK CAPITAL LETTER RHO
    { 0x03a3, NNN },  // GREEK CAPITAL LETTER SIGMA
    { 0x03a4, 'T' },  // GREEK CAPITAL LETTER TAU
    { 0x03a5, 'Y' },  // GREEK CAPITAL LETTER UPSILON
    { 0x03a6, NNN },  // GREEK CAPITAL LETTER PHI
    { 0x03a7, 'X' },  // GREEK CAPITAL LETTER CHI
    { 0x03a8, NNN },  // GREEK CAPITAL LETTER PSI
    { 0x03a9, NNN },  // GREEK CAPITAL LETTER OMEGA
    { 0x03aa, 'I' },  // GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
    { 0x03ab, 'Y' },  // GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
    { 0x03ac, 'a' },  // GREEK SMALL LETTER ALPHA WITH TONOS
    { 0x03ad, NNN },  // GREEK SMALL LETTER EPSILON WITH TONOS
    { 0x03ae, 'n' },  // GREEK SMALL LETTER ETA WITH TONOS
    { 0x03af, 'i' },  // GREEK SMALL LETTER IOTA WITH TONOS
    { 0x03b0, 'u' },  // GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
    { 0x03b1, 'a' },  // GREEK SMALL LETTER ALPHA
    { 0x03b2, 'B' },  // GREEK SMALL LETTER BETA
    { 0x03b3, 'Y' },  // GREEK SMALL LETTER GAMMA
    { 0x03b4, NNN },  // GREEK SMALL LETTER DELTA
    { 0x03b5, NNN },  // GREEK SMALL LETTER EPSILON
    { 0x03b6, NNN },  // GREEK SMALL LETTER ZETA
    { 0x03b7, 'n' },  // GREEK SMALL LETTER ETA
    { 0x03b8, NNN },  // GREEK SMALL LETTER THETA
    { 0x03b9, 'i' },  // GREEK SMALL LETTER IOTA
    { 0x03ba, 'k' },  // GREEK SMALL LETTER KAPPA
    { 0x03bb, NNN },  // GREEK SMALL LETTER LAMDA
    { 0x03bc, 'u' },  // GREEK SMALL LETTER MU
    { 0x03bd, 'v' },  // GREEK SMALL LETTER NU
    { 0x03be, NNN },  // GREEK SMALL LETTER XI
    { 0x03bf, 'o' },  // GREEK SMALL LETTER OMICRON
    { 0x03c0, NNN },  // GREEK SMALL LETTER PI
    { 0x03c1, 'p' },  // GREEK SMALL LETTER RHO
    { 0x03c2, NNN },  // GREEK SMALL LETTER FINAL SIGMA
    { 0x03c3, NNN },  // GREEK SMALL LETTER SIGMA
    { 0x03c4, 'T' },  // GREEK SMALL LETTER TAU
    { 0x03c5, 'u' },  // GREEK SMALL LETTER UPSILON
    { 0x03c6, NNN },  // GREEK SMALL LETTER PHI
    { 0x03c7, 'X' },  // GREEK SMALL LETTER CHI
    { 0x03c8, NNN },  // GREEK SMALL LETTER PSI
    { 0x03c9, 'w' },  // GREEK SMALL LETTER OMEGA
    { 0x03ca, 'i' },  // GREEK SMALL LETTER IOTA WITH DIALYTIKA
    { 0x03cb, 'u' },  // GREEK SMALL LETTER UPSILON WITH DIALYTIKA
    { 0x03cc, 'o' },  // GREEK SMALL LETTER OMICRON WITH TONOS
    { 0x03cd, 'u' },  // GREEK SMALL LETTER UPSILON WITH TONOS
    { 0x03ce, 'w' },  // GREEK SMALL LETTER OMEGA WITH TONOS

    // Cyrillic alphabets cannot be easily mapped to 7-bit ASCII,
	// but for many glyphs a sane fallback is feasible.
    { 0x0401, 'E' },  // CYRILLIC CAPITAL LETTER IO
    { 0x0402, NNN },  // CYRILLIC CAPITAL LETTER DJE
    { 0x0403, NNN },  // CYRILLIC CAPITAL LETTER GJE
    { 0x0404, NNN },  // CYRILLIC CAPITAL LETTER UKRAINIAN IE
    { 0x0405, 'S' },  // CYRILLIC CAPITAL LETTER DZE
    { 0x0406, 'I' },  // CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I
    { 0x0407, 'I' },  // CYRILLIC CAPITAL LETTER YI
    { 0x0408, 'J' },  // CYRILLIC CAPITAL LETTER JE
    { 0x0409, NNN },  // CYRILLIC CAPITAL LETTER LJE
    { 0x040a, NNN },  // CYRILLIC CAPITAL LETTER NJE
    { 0x040b, NNN },  // CYRILLIC CAPITAL LETTER TSHE
    { 0x040c, 'K' },  // CYRILLIC CAPITAL LETTER KJE
    { 0x040e, 'y' },  // CYRILLIC CAPITAL LETTER SHORT U
    { 0x040f, 'U' },  // CYRILLIC CAPITAL LETTER DZHE
    { 0x0410, 'A' },  // CYRILLIC CAPITAL LETTER A
    { 0x0411, NNN },  // CYRILLIC CAPITAL LETTER BE
    { 0x0412, 'B' },  // CYRILLIC CAPITAL LETTER VE
    { 0x0413, NNN },  // CYRILLIC CAPITAL LETTER GHE
    { 0x0414, NNN },  // CYRILLIC CAPITAL LETTER DE
    { 0x0415, 'E' },  // CYRILLIC CAPITAL LETTER IE
    { 0x0416, NNN },  // CYRILLIC CAPITAL LETTER ZHE
    { 0x0417, '3' },  // CYRILLIC CAPITAL LETTER ZE
    { 0x0418, NNN },  // CYRILLIC CAPITAL LETTER I
    { 0x0419, NNN },  // CYRILLIC CAPITAL LETTER SHORT I
    { 0x041a, 'K' },  // CYRILLIC CAPITAL LETTER KA
    { 0x041b, NNN },  // CYRILLIC CAPITAL LETTER EL
    { 0x041c, 'M' },  // CYRILLIC CAPITAL LETTER EM
    { 0x041d, 'H' },  // CYRILLIC CAPITAL LETTER EN
    { 0x041e, 'O' },  // CYRILLIC CAPITAL LETTER O
    { 0x041f, NNN },  // CYRILLIC CAPITAL LETTER PE
    { 0x0420, 'P' },  // CYRILLIC CAPITAL LETTER ER
    { 0x0421, 'C' },  // CYRILLIC CAPITAL LETTER ES
    { 0x0422, 'T' },  // CYRILLIC CAPITAL LETTER TE
    { 0x0423, 'y' },  // CYRILLIC CAPITAL LETTER U
    { 0x0424, NNN },  // CYRILLIC CAPITAL LETTER EF
    { 0x0425, 'X' },  // CYRILLIC CAPITAL LETTER HA
    { 0x0426, NNN },  // CYRILLIC CAPITAL LETTER TSE
    { 0x0427, NNN },  // CYRILLIC CAPITAL LETTER CHE
    { 0x0428, 'W' },  // CYRILLIC CAPITAL LETTER SHA
    { 0x0429, 'W' },  // CYRILLIC CAPITAL LETTER SHCHA
    { 0x042a, 'b' },  // CYRILLIC CAPITAL LETTER HARD SIGN
    { 0x042b, NNN },  // CYRILLIC CAPITAL LETTER YERU
    { 0x042c, 'b' },  // CYRILLIC CAPITAL LETTER SOFT SIGN
    { 0x042d, '3' },  // CYRILLIC CAPITAL LETTER E
    { 0x042e, NNN },  // CYRILLIC CAPITAL LETTER YU
    { 0x042f, NNN },  // CYRILLIC CAPITAL LETTER YA
    { 0x0430, 'a' },  // CYRILLIC SMALL LETTER A
    { 0x0431, NNN },  // CYRILLIC SMALL LETTER BE
    { 0x0432, 'B' },  // CYRILLIC SMALL LETTER VE
    { 0x0433, 'r' },  // CYRILLIC SMALL LETTER GHE
    { 0x0434, NNN },  // CYRILLIC SMALL LETTER DE
    { 0x0435, 'e' },  // CYRILLIC SMALL LETTER IE
    { 0x0436, NNN },  // CYRILLIC SMALL LETTER ZHE
    { 0x0437, '3' },  // CYRILLIC SMALL LETTER ZE
    { 0x0438, NNN },  // CYRILLIC SMALL LETTER I
    { 0x0439, NNN },  // CYRILLIC SMALL LETTER SHORT I
    { 0x043a, 'k' },  // CYRILLIC SMALL LETTER KA
    { 0x043b, NNN },  // CYRILLIC SMALL LETTER EL
    { 0x043c, 'M' },  // CYRILLIC SMALL LETTER EM
    { 0x043d, 'H' },  // CYRILLIC SMALL LETTER EN
    { 0x043e, 'o' },  // CYRILLIC SMALL LETTER O
    { 0x043f, NNN },  // CYRILLIC SMALL LETTER PE
    { 0x0440, 'p' },  // CYRILLIC SMALL LETTER ER
    { 0x0441, 'c' },  // CYRILLIC SMALL LETTER ES
    { 0x0442, 'T' },  // CYRILLIC SMALL LETTER TE
    { 0x0443, 'y' },  // CYRILLIC SMALL LETTER U
    { 0x0444, NNN },  // CYRILLIC SMALL LETTER EF
    { 0x0445, 'x' },  // CYRILLIC SMALL LETTER HA
    { 0x0446, 'u' },  // CYRILLIC SMALL LETTER TSE
    { 0x0447, NNN },  // CYRILLIC SMALL LETTER CHE
    { 0x0448, 'w' },  // CYRILLIC SMALL LETTER SHA
    { 0x0449, 'w' },  // CYRILLIC SMALL LETTER SHCHA
    { 0x044a, 'b' },  // CYRILLIC SMALL LETTER HARD SIGN
    { 0x044b, NNN },  // CYRILLIC SMALL LETTER YERU
    { 0x044c, 'b' },  // CYRILLIC SMALL LETTER SOFT SIGN
    { 0x044d, '3' },  // CYRILLIC SMALL LETTER E
    { 0x044e, NNN },  // CYRILLIC SMALL LETTER YU
    { 0x044f, NNN },  // CYRILLIC SMALL LETTER YA
    { 0x0450, 'e' },  // CYRILLIC SMALL LETTER E WITH GRAVE
    { 0x0451, 'e' },  // CYRILLIC SMALL LETTER IO
    { 0x0452, 'h' },  // CYRILLIC SMALL LETTER DJE
    { 0x0453, NNN },  // CYRILLIC SMALL LETTER GJE
    { 0x0454, NNN },  // CYRILLIC SMALL LETTER UKRAINIAN IE
    { 0x0455, 's' },  // CYRILLIC SMALL LETTER DZE
    { 0x0456, 'i' },  // CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
    { 0x0457, 'i' },  // CYRILLIC SMALL LETTER YI
    { 0x0458, 'j' },  // CYRILLIC SMALL LETTER JE
    { 0x0459, NNN },  // CYRILLIC SMALL LETTER LJE
    { 0x045a, NNN },  // CYRILLIC SMALL LETTER NJE
    { 0x045b, 'h' },  // CYRILLIC SMALL LETTER TSHE
    { 0x045c, 'k' },  // CYRILLIC SMALL LETTER KJE
    { 0x045e, 'y' },  // CYRILLIC SMALL LETTER SHORT U
    { 0x045f, 'u' },  // CYRILLIC SMALL LETTER DZHE

    // Hebrew script cannot be easily mapped to 7-bit ASCII,
	// but for some glyphs a sane fallback is feasible.
    { 0x05d0, 'x' },  // HEBREW LETTER ALEF
    { 0x05d1, NNN },  // HEBREW LETTER BET
    { 0x05d2, NNN },  // HEBREW LETTER GIMEL
    { 0x05d3, NNN },  // HEBREW LETTER DALET
    { 0x05d4, NNN },  // HEBREW LETTER HE
    { 0x05d5, 'i' },  // HEBREW LETTER VAV
    { 0x05d6, NNN },  // HEBREW LETTER ZAYIN
    { 0x05d7, 'n' },  // HEBREW LETTER HET
    { 0x05d8, NNN },  // HEBREW LETTER TET
    { 0x05d9, '\'' }, // HEBREW LETTER YOD
    { 0x05da, NNN },  // HEBREW LETTER FINAL KAF
    { 0x05db, NNN },  // HEBREW LETTER KAF
    { 0x05dc, NNN },  // HEBREW LETTER LAMED
    { 0x05dd, NNN },  // HEBREW LETTER FINAL MEM
    { 0x05de, NNN },  // HEBREW LETTER MEM
    { 0x05df, 'I' },  // HEBREW LETTER FINAL NUN
    { 0x05e0, NNN },  // HEBREW LETTER NUN
    { 0x05e1, 'o' },  // HEBREW LETTER SAMEKH
    { 0x05e2, 'y' },  // HEBREW LETTER AYIN
    { 0x05e3, NNN },  // HEBREW LETTER FINAL PE
    { 0x05e4, NNN },  // HEBREW LETTER PE
    { 0x05e5, 'Y' },  // HEBREW LETTER FINAL TSADI
    { 0x05e6, NNN },  // HEBREW LETTER TSADI
    { 0x05e7, NNN },  // HEBREW LETTER QOF
    { 0x05e8, NNN },  // HEBREW LETTER RESH
    { 0x05e9, NNN },  // HEBREW LETTER SHIN
    { 0x05ea, NNN },  // HEBREW LETTER TAV

    { 0x060c, ',' },  // ARABIC COMMA
    { 0x061b, ';' },  // ARABIC SEMICOLON
    { 0x061f, '?' },  // ARABIC QUESTION MARK
    { 0x0640, '-' },  // ARABIC TATWEEL
    { 0x0651, NNN },  // ARABIC SHADDAH

	// Indo-Arabic numerals have lowest-value digits to the right,
	// so it is safe to replace them with ASCII digits.
    { 0x0660, '0' },  // ARABIC-INDIC DIGIT ZERO
    { 0x0661, '1' },  // ARABIC-INDIC DIGIT ONE
    { 0x0662, '2' },  // ARABIC-INDIC DIGIT TWO
    { 0x0663, '3' },  // ARABIC-INDIC DIGIT THREE
    { 0x0664, '4' },  // ARABIC-INDIC DIGIT FOUR
    { 0x0665, '5' },  // ARABIC-INDIC DIGIT FIVE
    { 0x0666, '6' },  // ARABIC-INDIC DIGIT SIX
    { 0x0667, '7' },  // ARABIC-INDIC DIGIT SEVEN
    { 0x0668, '8' },  // ARABIC-INDIC DIGIT EIGHT
    { 0x0669, '9' },  // ARABIC-INDIC DIGIT NINE

    // Thai script cannot be mapped to 7-bit ASCII at all.
    { 0x0E01, NNN },  // THAI CHARACTER KO KAI
    { 0x0E02, NNN },  // THAI CHARACTER KHO KHAI
    { 0x0E03, NNN },  // THAI CHARACTER KHO KHUAT
    { 0x0E04, NNN },  // THAI CHARACTER KHO KHWAI
    { 0x0E05, NNN },  // THAI CHARACTER KHO KHON
    { 0x0E06, NNN },  // THAI CHARACTER KHO RAKHANG
    { 0x0E07, NNN },  // THAI CHARACTER NGO NGU
    { 0x0E08, NNN },  // THAI CHARACTER CHO CHAN
    { 0x0E09, NNN },  // THAI CHARACTER CHO CHING
    { 0x0E0A, NNN },  // THAI CHARACTER CHO CHANG
    { 0x0E0B, NNN },  // THAI CHARACTER SO SO
    { 0x0E0C, NNN },  // THAI CHARACTER CHO CHOE
    { 0x0E0D, NNN },  // THAI CHARACTER YO YING
    { 0x0E0E, NNN },  // THAI CHARACTER DO CHADA
    { 0x0E0F, NNN },  // THAI CHARACTER TO PATAK
    { 0x0E10, NNN },  // THAI CHARACTER THO THAN
    { 0x0E11, NNN },  // THAI CHARACTER THO NANGMONTHO
    { 0x0E12, NNN },  // THAI CHARACTER THO PHUTHAO
    { 0x0E13, NNN },  // THAI CHARACTER NO NEN
    { 0x0E14, NNN },  // THAI CHARACTER DO DEK
    { 0x0E15, NNN },  // THAI CHARACTER TO TAO
    { 0x0E16, NNN },  // THAI CHARACTER THO THUNG
    { 0x0E17, NNN },  // THAI CHARACTER THO THAHAN
    { 0x0E18, NNN },  // THAI CHARACTER THO THONG
    { 0x0E19, NNN },  // THAI CHARACTER NO NU
    { 0x0E1A, NNN },  // THAI CHARACTER BO BAIMAI
    { 0x0E1B, NNN },  // THAI CHARACTER PO PLA
    { 0x0E1C, NNN },  // THAI CHARACTER PHO PHUNG
    { 0x0E1D, NNN },  // THAI CHARACTER FO FA
    { 0x0E1E, NNN },  // THAI CHARACTER PHO PHAN
    { 0x0E1F, NNN },  // THAI CHARACTER FO FAN
    { 0x0E20, NNN },  // THAI CHARACTER PHO SAMPHAO
    { 0x0E21, NNN },  // THAI CHARACTER MO MA
    { 0x0E22, NNN },  // THAI CHARACTER YO YAK
    { 0x0E23, NNN },  // THAI CHARACTER RO RUA
    { 0x0E24, NNN },  // THAI CHARACTER RU
    { 0x0E25, NNN },  // THAI CHARACTER LO LING
    { 0x0E26, NNN },  // THAI CHARACTER LU
    { 0x0E27, NNN },  // THAI CHARACTER WO WAEN
    { 0x0E28, NNN },  // THAI CHARACTER SO SALA
    { 0x0E29, NNN },  // THAI CHARACTER SO RUSI
    { 0x0E2A, NNN },  // THAI CHARACTER SO SUA
    { 0x0E2B, NNN },  // THAI CHARACTER HO HIP
    { 0x0E2C, NNN },  // THAI CHARACTER LO CHULA
    { 0x0E2D, NNN },  // THAI CHARACTER O ANG
    { 0x0E2E, NNN },  // THAI CHARACTER HO NOKHUK
    { 0x0E2F, NNN },  // THAI CHARACTER PAIYANNOI
    { 0x0E30, NNN },  // THAI CHARACTER SARA A
    { 0x0E31, NNN },  // THAI CHARACTER MAI HAN-AKAT
    { 0x0E32, NNN },  // THAI CHARACTER SARA AA
    { 0x0E33, NNN },  // THAI CHARACTER SARA AM
    { 0x0E34, NNN },  // THAI CHARACTER SARA I
    { 0x0E35, NNN },  // THAI CHARACTER SARA II
    { 0x0E36, NNN },  // THAI CHARACTER SARA UE
    { 0x0E37, NNN },  // THAI CHARACTER SARA UEE
    { 0x0E38, NNN },  // THAI CHARACTER SARA U
    { 0x0E39, NNN },  // THAI CHARACTER SARA UU
    { 0x0E3A, NNN },  // THAI CHARACTER PHINTHU
    { 0x0E3F, NNN },  // THAI CURRENCY SYMBOL BAHT
    { 0x0E40, NNN },  // THAI CHARACTER SARA E
    { 0x0E41, NNN },  // THAI CHARACTER SARA AE
    { 0x0E42, NNN },  // THAI CHARACTER SARA O
    { 0x0E43, NNN },  // THAI CHARACTER SARA AI MAIMUAN
    { 0x0E44, NNN },  // THAI CHARACTER SARA AI MAIMALAI
    { 0x0E45, NNN },  // THAI CHARACTER LAKKHANGYAO
    { 0x0E46, NNN },  // THAI CHARACTER MAIYAMOK
    { 0x0E47, NNN },  // THAI CHARACTER MAITAIKHU
    { 0x0E48, NNN },  // THAI CHARACTER MAI EK
    { 0x0E49, NNN },  // THAI CHARACTER MAI THO
    { 0x0E4A, NNN },  // THAI CHARACTER MAI TRI
    { 0x0E4B, NNN },  // THAI CHARACTER MAI CHATTAWA
    { 0x0E4C, NNN },  // THAI CHARACTER THANTHAKHAT
    { 0x0E4D, NNN },  // THAI CHARACTER NIKHAHIT
    { 0x0E4E, NNN },  // THAI CHARACTER YAMAKKAN
    { 0x0E4F, NNN },  // THAI CHARACTER FONGMAN

	// Thai numerals have lowest-value digits to the right,
	// so it is safe to replace them with ASCII digits.
    { 0x0E50, '0' },  // THAI DIGIT ZERO
    { 0x0E51, '1' },  // THAI DIGIT ONE
    { 0x0E52, '2' },  // THAI DIGIT TWO
    { 0x0E53, '3' },  // THAI DIGIT THREE
    { 0x0E54, '4' },  // THAI DIGIT FOUR
    { 0x0E55, '5' },  // THAI DIGIT FIVE
    { 0x0E56, '6' },  // THAI DIGIT SIX
    { 0x0E57, '7' },  // THAI DIGIT SEVEN
    { 0x0E58, '8' },  // THAI DIGIT EIGHT
    { 0x0E59, '9' },  // THAI DIGIT NINE

    { 0x0E5A, NNN },  // THAI CHARACTER ANGKHANKHU
    { 0x0E5B, NNN },  // THAI CHARACTER KHOMUT

    { 0x2013, '-' },  // EN DASH
    { 0x2014, '-' },  // EM DASH
    { 0x2015, '-' },  // HORIZONTAL BAR
    { 0x2017, NNN },  // DOUBLE LOW LINE
    { 0x2018, '\'' },  // LEFT SINGLE QUOTATION MARK
    { 0x2019, '\'' }, // RIGHT SINGLE QUOTATION MARK
    { 0x201c, '"' },  // LEFT DOUBLE QUOTATION MARK
    { 0x201d, '"' },  // RIGHT DOUBLE QUOTATION MARK
    { 0x201e, '"' },  // DOUBLE LOW-9 QUOTATION MARK
    { 0x2022, '-' },  // BULLET
    { 0x2026, '.' },  // HORIZONTAL ELLIPSIS
    { 0x207f, NNN },  // SUPERSCRIPT LATIN SMALL LETTER N
    { 0x20a7, 'P' },  // PESETA SIGN
    { 0x20ac, 'E' },  // EURO SIGN
    { 0x2116, '#' },  // NUMERO SIGN
    { 0x2126, NNN },  // OHM SIGN
    { 0x2208, NNN },  // ELEMENT OF
    { 0x2211, NNN },  // N-ARY SUMMATION
    { 0x2219, '-' },  // BULLET OPERATOR
    { 0x221a, NNN },  // SQUARE ROOT
    { 0x221e, NNN },  // INFINITY
    { 0x2229, NNN },  // INTERSECTION
    { 0x2248, NNN },  // ALMOST EQUAL TO
    { 0x2261, '=' },  // IDENTICAL TO
    { 0x2264, NNN },  // LESS-THAN OR EQUAL TO
    { 0x2265, NNN },  // GREATER-THAN OR EQUAL TO
    { 0x2310, '~' },  // REVERSED NOT SIGN
    { 0x2320, '|' },  // TOP HALF INTEGRAL
    { 0x2321, '|' },  // BOTTOM HALF INTEGRAL

	// Replace box drawing glyphs with characters which at least
	// produce reasonably ellegant tables.
    { 0x2500, '-' },  // BOX DRAWINGS LIGHT HORIZONTAL
    { 0x2502, '|' },  // BOX DRAWINGS LIGHT VERTICAL
    { 0x250c, '+' },  // BOX DRAWINGS LIGHT DOWN AND RIGHT
    { 0x2510, '+' },  // BOX DRAWINGS LIGHT DOWN AND LEFT
    { 0x2514, '+' },  // BOX DRAWINGS LIGHT UP AND RIGHT
    { 0x2518, '+' },  // BOX DRAWINGS LIGHT UP AND LEFT
    { 0x251c, '+' },  // BOX DRAWINGS LIGHT VERTICAL AND RIGHT
    { 0x2524, '+' },  // BOX DRAWINGS LIGHT VERTICAL AND LEFT
    { 0x252c, '+' },  // BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
    { 0x2534, '+' },  // BOX DRAWINGS LIGHT UP AND HORIZONTAL
    { 0x253c, '+' },  // BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
    { 0x2550, '-' },  // BOX DRAWINGS DOUBLE HORIZONTAL
    { 0x2551, '|' },  // BOX DRAWINGS DOUBLE VERTICAL
    { 0x2552, '+' },  // BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE
    { 0x2553, '+' },  // BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE
    { 0x2554, '+' },  // BOX DRAWINGS DOUBLE DOWN AND RIGHT
    { 0x2555, '+' },  // BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE
    { 0x2556, '+' },  // BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE
    { 0x2557, '+' },  // BOX DRAWINGS DOUBLE DOWN AND LEFT
    { 0x2558, '+' },  // BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE
    { 0x2559, '+' },  // BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE
    { 0x255a, '+' },  // BOX DRAWINGS DOUBLE UP AND RIGHT
    { 0x255b, '+' },  // BOX DRAWINGS UP SINGLE AND LEFT DOUBLE
    { 0x255c, '+' },  // BOX DRAWINGS UP DOUBLE AND LEFT SINGLE
    { 0x255d, '+' },  // BOX DRAWINGS DOUBLE UP AND LEFT
    { 0x255e, '+' },  // BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE
    { 0x255f, '+' },  // BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE
    { 0x2560, '+' },  // BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
    { 0x2561, '+' },  // BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE
    { 0x2562, '+' },  // BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE
    { 0x2563, '+' },  // BOX DRAWINGS DOUBLE VERTICAL AND LEFT
    { 0x2564, '+' },  // BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE
    { 0x2565, '+' },  // BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE
    { 0x2566, '+' },  // BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
    { 0x2567, '+' },  // BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE
    { 0x2568, '+' },  // BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE
    { 0x2569, '+' },  // BOX DRAWINGS DOUBLE UP AND HORIZONTAL
    { 0x256a, '+' },  // BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE
    { 0x256b, '+' },  // BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE
    { 0x256c, '+' },  // BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL

    { 0x2580, NNN },  // UPPER HALF BLOCK
    { 0x2584, NNN },  // LOWER HALF BLOCK
    { 0x2588, NNN },  // FULL BLOCK
    { 0x258c, NNN },  // LEFT HALF BLOCK
    { 0x2590, NNN },  // RIGHT HALF BLOCK
    { 0x2591, NNN },  // LIGHT SHADE
    { 0x2592, NNN },  // MEDIUM SHADE
    { 0x2593, NNN },  // DARK SHADE
    { 0x25a0, NNN },  // BLACK SQUARE

    // Arabic scripts cannot be mapped to 7-bit ASCII at all.
    { 0xfe7d, NNN },  // ARABIC SHADDA MEDIAL FORM
    { 0xfe80, NNN },  // ARABIC LETTER HAMZA ISOLATED FORM
    { 0xfe81, NNN },  // ARABIC LETTER ALEF WITH MADDA ABOVE ISOLATED FORM
    { 0xfe82, NNN },  // ARABIC LETTER ALEF WITH MADDA ABOVE FINAL FORM
    { 0xfe83, NNN },  // ARABIC LETTER ALEF WITH HAMZA ABOVE ISOLATED FORM
    { 0xfe84, NNN },  // ARABIC LETTER ALEF WITH HAMZA ABOVE FINAL FORM
    { 0xfe85, NNN },  // ARABIC LETTER WAW WITH HAMZA ABOVE ISOLATED FORM
    { 0xfe8b, NNN },  // ARABIC LETTER YEH WITH HAMZA ABOVE INITIAL FORM
    { 0xfe8d, NNN },  // ARABIC LETTER ALEF ISOLATED FORM
    { 0xfe8e, NNN },  // ARABIC LETTER ALEF FINAL FORM
    { 0xfe8f, NNN },  // ARABIC LETTER BEH ISOLATED FORM
    { 0xfe91, NNN },  // ARABIC LETTER BEH INITIAL FORM
    { 0xfe93, NNN },  // ARABIC LETTER TEH MARBUTA ISOLATED FORM
    { 0xfe95, NNN },  // ARABIC LETTER TEH ISOLATED FORM
    { 0xfe97, NNN },  // ARABIC LETTER TEH INITIAL FORM
    { 0xfe99, NNN },  // ARABIC LETTER THEH ISOLATED FORM
    { 0xfe9b, NNN },  // ARABIC LETTER THEH INITIAL FORM
    { 0xfe9d, NNN },  // ARABIC LETTER JEEM ISOLATED FORM
    { 0xfe9f, NNN },  // ARABIC LETTER JEEM INITIAL FORM
    { 0xfea1, NNN },  // ARABIC LETTER HAH ISOLATED FORM
    { 0xfea3, NNN },  // ARABIC LETTER HAH INITIAL FORM
    { 0xfea5, NNN },  // ARABIC LETTER KHAH ISOLATED FORM
    { 0xfea7, NNN },  // ARABIC LETTER KHAH INITIAL FORM
    { 0xfea9, NNN },  // ARABIC LETTER DAL ISOLATED FORM
    { 0xfeab, NNN },  // ARABIC LETTER THAL ISOLATED FORM
    { 0xfead, NNN },  // ARABIC LETTER REH ISOLATED FORM
    { 0xfeaf, NNN },  // ARABIC LETTER ZAIN ISOLATED FORM
    { 0xfeb1, NNN },  // ARABIC LETTER SEEN ISOLATED FORM
    { 0xfeb3, NNN },  // ARABIC LETTER SEEN INITIAL FORM
    { 0xfeb5, NNN },  // ARABIC LETTER SHEEN ISOLATED FORM
    { 0xfeb7, NNN },  // ARABIC LETTER SHEEN INITIAL FORM
    { 0xfeb9, NNN },  // ARABIC LETTER SAD ISOLATED FORM
    { 0xfebb, NNN },  // ARABIC LETTER SAD INITIAL FORM
    { 0xfebd, NNN },  // ARABIC LETTER DAD ISOLATED FORM
    { 0xfebf, NNN },  // ARABIC LETTER DAD INITIAL FORM
    { 0xfec1, NNN },  // ARABIC LETTER TAH ISOLATED FORM
    { 0xfec5, NNN },  // ARABIC LETTER ZAH ISOLATED FORM
    { 0xfec9, NNN },  // ARABIC LETTER AIN ISOLATED FORM
    { 0xfeca, NNN },  // ARABIC LETTER AIN FINAL FORM
    { 0xfecb, NNN },  // ARABIC LETTER AIN INITIAL FORM
    { 0xfecc, NNN },  // ARABIC LETTER AIN MEDIAL FORM
    { 0xfecd, NNN },  // ARABIC LETTER GHAIN ISOLATED FORM
    { 0xfece, NNN },  // ARABIC LETTER GHAIN FINAL FORM
    { 0xfecf, NNN },  // ARABIC LETTER GHAIN INITIAL FORM
    { 0xfed0, NNN },  // ARABIC LETTER GHAIN MEDIAL FORM
    { 0xfed1, NNN },  // ARABIC LETTER FEH ISOLATED FORM
    { 0xfed3, NNN },  // ARABIC LETTER FEH INITIAL FORM
    { 0xfed5, NNN },  // ARABIC LETTER QAF ISOLATED FORM
    { 0xfed7, NNN },  // ARABIC LETTER QAF INITIAL FORM
    { 0xfed9, NNN },  // ARABIC LETTER KAF ISOLATED FORM
    { 0xfedb, NNN },  // ARABIC LETTER KAF INITIAL FORM
    { 0xfedd, NNN },  // ARABIC LETTER LAM ISOLATED FORM
    { 0xfedf, NNN },  // ARABIC LETTER LAM INITIAL FORM
    { 0xfee1, NNN },  // ARABIC LETTER MEEM ISOLATED FORM
    { 0xfee3, NNN },  // ARABIC LETTER MEEM INITIAL FORM
    { 0xfee5, NNN },  // ARABIC LETTER NOON ISOLATED FORM
    { 0xfee7, NNN },  // ARABIC LETTER NOON INITIAL FORM
    { 0xfee9, NNN },  // ARABIC LETTER HEH ISOLATED FORM
    { 0xfeeb, NNN },  // ARABIC LETTER HEH INITIAL FORM
    { 0xfeec, NNN },  // ARABIC LETTER HEH MEDIAL FORM
    { 0xfeed, NNN },  // ARABIC LETTER WAW ISOLATED FORM
    { 0xfeef, NNN },  // ARABIC LETTER ALEF MAKSURA ISOLATED FORM
    { 0xfef0, NNN },  // ARABIC LETTER ALEF MAKSURA FINAL FORM
    { 0xfef1, NNN },  // ARABIC LETTER YEH ISOLATED FORM
    { 0xfef2, NNN },  // ARABIC LETTER YEH FINAL FORM
    { 0xfef3, NNN },  // ARABIC LETTER YEH INITIAL FORM
    { 0xfef5, NNN },  // ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE ISOLATED FORM
    { 0xfef6, NNN },  // ARABIC LIGATURE LAM WITH ALEF WITH MADDA ABOVE FINAL FORM
    { 0xfef7, NNN },  // ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE ISOLATED FORM
    { 0xfef8, NNN },  // ARABIC LIGATURE LAM WITH ALEF WITH HAMZA ABOVE FINAL FORM
    { 0xfefb, NNN },  // ARABIC LIGATURE LAM WITH ALEF ISOLATED FORM
    { 0xfefc, NNN },  // ARABIC LIGATURE LAM WITH ALEF FINAL FORM
};

#undef NNN
