extraction:
  python:
    python_setup:
      version: 3

  cpp:
    prepare:
      packages:
      - libasound2-dev
      - libfreetype-dev
      - libopusfile-dev
      - libpng-dev
      - libsdl2-dev
      - libsdl2-net-dev
      - libspeexdsp-dev
      - python3-pip
    after_prepare:
    - python3 -m pip install --user --upgrade meson
    - export PATH="$HOME/.local/bin:$PATH"
    - meson --version
    configure:
      command:
      - meson setup -Duse_fluidsynth=false -Duse_mt32emu=false -Dunit_tests=disabled build
    index:
      build_command:
      - ninja -C build

queries:
- exclude: cpp/short-global-name
