#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2024-2026 The DOSBox Staging Team

# Repackages the Windows ZIP release package generated by the CI workflow
# under a parent directory.
#
# Prerequisites: zip & unzip commands

set -e

if [ $# -ne 1 ]; then
	echo "Usage: repackage-windows-zip.sh CI_ZIP_NAME"
	exit 1
fi

IN_ZIP=$1

if [[ $IN_ZIP != $IN_ZIP_PREFIX* ]]; then
	echo "Input filename must start with '$IN_ZIP_PREFIX'"
	exit 1
fi

if [[ $IN_ZIP =~ ^.*/dosbox-staging-windows-([^-]*)-(v?)([0-9.]*)- ]]; then
    ARCH=${BASH_REMATCH[1]}
    VERSION=${BASH_REMATCH[3]}
else
	echo "Invalid input filename pattern"
	exit 1
fi

ROOT_DIR=dosbox-staging-v$VERSION
OUT_ZIP=dosbox-staging-windows-$ARCH-v$VERSION.zip

rm -rf "$ROOT_DIR"
mkdir "$ROOT_DIR"

unzip -q "$IN_ZIP" -d "$ROOT_DIR"
rm "$ROOT_DIR/release-notes.html"
zip -q -r "$OUT_ZIP" "$ROOT_DIR"

rm -rf "$ROOT_DIR"

echo "Created Windows portable ZIP package: $OUT_ZIP"
