name: Question
description: Ask for support or start a discussion.
labels: question
#assignees: 'anonymous@temp'

body:
  - type: markdown
    attributes:
      value: |
        ## Please fill out forms as cleanly as possible.
        #### Make sure that you have
        * properly edited & filled in the title of this bug report
  - type: checkboxes
    id: version
    attributes:
      label: Are you using the latest Dosbox-Staging Version?
      description: |
        What version are you using? Check the [latest release](https://github.com/dosbox-staging/dosbox-staging/releases)
        Run `dosbox --version`
        Type `ver` command inside DOSBox shell; If the version is reported as `git` (meaning you compiled it yourself), use `git describe` command.
        Provide 'git' version or 'other' in description
      options:
        - label: I have checked releases and am using the latest release.
          required: true
  - type: input
    id: verinfo
    attributes:
      label: Different version than latest?
      description: Alpha, Git, or Branch?
      placeholder: "Ex. 0.81.0-alpha, git verion, branch testing."
    validations:
      required: false
  - type: dropdown
    id: OS
    attributes:
      label: What Operating System are you using?
      multiple: false
      options:
        - Windows 11
        - Windows 10
        - Windows 8
        - Windows 7
        - Windows Other
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux x86
        - Linux x86_64
        - Linux ppc64le
        - Linux ARM (Raspberry Pi)
        - Other
    validations:
      required: false
  - type: textarea
    id: question
    attributes:
      label: Whats your question and how can we help?
      description: Ask us a question
      placeholder: "How do I ..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct & Contributing Guidelines
      description: By submitting this issue, you agree to follow our [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
      options:
        - label: Yes, I agree.
          required: true
