name:        Question
description: Ask for support or start a discussion
title:       Think about the title, twice
labels:      question

body:
  - type: markdown
    id: intro
    attributes:
      value: |
        ## Please fill out the form completely. Incomplete submissions will be closed!
        #### Make sure that you have:
        - provided a descriptive and succinct title
        - have read all questions carefully have answered **all** of them

        [Please consider a donation to the DOSBox Staging project](https://www.dosbox-staging.org/get-involved/#make-a-donation).

  - type: checkboxes
    id: version
    attributes:
      label: Are you using the latest DOSBox Staging version?
      description: |
        Look up the latest release version [on our website](https://www.dosbox-staging.org/) or the [releases page](https://github.com/dosbox-staging/dosbox-staging/releases).
        To check your version, run `dosbox --version` or execute the `VER` command inside DOSBox Staging. If the version is reported as `git` (meaning you compiled it yourself), put the result of `git describe` in the version field below.
      options:
        - label: I have checked and I'm using the latest release.
          required: true

  - type: input
    id: verinfo
    attributes:
      label: Different version than latest?
      placeholder: "E.g., 0.83.0-alpha, git version, branch testing"
    validations:
      required: false

  - type: dropdown
    id: OS
    attributes:
      label: What operating system are you using?
      multiple: false
      options:
        - Please select
        - Windows 11
        - Windows 10
        - Windows 8
        - Windows 7
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux x86
        - Linux x86_64
        - Linux ARM (Raspberry Pi)
        - Other
    validations:
      required: true

  - type: input
    id: other
    attributes:
      label: If other OS or Linux, please describe
      placeholder: "Details about your OS; if Linux, state your desktop environment (KDE, Gnome, XFCE, etc.)"
    validations:
      required: false

  - type: checkboxes
    id: checked
    attributes:
      label: Are you running DOSBox Staging on a native OS?
      description: We only support running DOSBox Staging on a native operating system; running on a guest OS in a VM or hypervisor is not supported.
      options:
        - label: I am running Staging on a native OS
          required: true

  - type: textarea
    id: question
    attributes:
      label: What is your question and how can we help?
      description: Ask us a question
      placeholder: "How do I ..."
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of conduct and contributing guidelines
      description: By submitting this issue, you agree to follow our [contributing guidelines](https://github.com/dosbox-staging/dosbox-staging/blob/master/docs/CONTRIBUTING.md) and [code of conduct](https://github.com/dosbox-staging/dosbox-staging/blob/master/CODE_OF_CONDUCT.md).
      options:
        - label: Yes, I agree.
          required: true
