name: Build documentation
description: Build offline documentation for inclusion in build artifacts

runs:
  using: composite
  steps:
    - name: Install mkdocs
      shell: bash
      run:
        pip3 install -r extras/documentation/mkdocs-package-requirements.txt

    - name: Build documentation
      shell: bash
      run: |
        OFFLINE=true mkdocs build --config-file website/mkdocs.yml \
                                  --site-dir ../documentation
