.\"                                      Hey, EMACS: -*- nroff -*-
.TH DOSBOX 1 "March 31, 2003"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
dosbox \- an x86/DOS emulator with sound/graphics primarily for games
.SH SYNOPSIS
.B dosbox
[\fB-fullscreen\fR]
[\fB-conf\fR \fIconfigfile\fR]
[\fB-lang\fR \fIlangfile\fR]
[\fBfile\fR]
[\fB-c\fR \fIcommand1\fR <\fIcommand2\fR>...]
.br
.SH DESCRIPTION
This manual page briefly documents
\fBdosbox\fR, an x86/DOS emulator capable of running many games.
.TP
The optional \fBfile\fR argument should be a DOS executable or a directory. If it is a dos executable (.com .exe .bat) the program will run automatically. If it is a directory, a DOS session will run with the directory mounted as C:.
.SH OPTIONS
A summary of options is included below.
.TP
\fB-fullscreen\fR
Start DOSBox in fullscreen mode
.TP
\fB-c\fR \fIcommand 1\fR [\fIcommand 2\fR] ...
Run one or more DOS commands after starting \fBdosbox\fR. If an executable is
also specified, these commands will be executed before running the program.
.TP
\fB-conf\fR \fIconfigfile\fR
Start \fBdosbox\fR with the options specified in \fIconfigfile\fR
.TP
\fB-lang\fR \fIlangfile\fR
Start \fBdosbox\fR with the language specified in \fIlangfile\fR
.SH INTERNAL COMMANDS
.B dosbox
supports most of the DOS commands found in command.com. In addition, the
following extra commands are available:
.TP
\fBMOUNT\fR [\fB-t\fR \fItype\fR] [\fB-size\fR \fIsize\fR] \fBdriveletter\fR \fBsourcedirectory\fR [\fB-aspi\fR]
Map \fBsourcedirectory\fR to \fBdriveletter\fR.
\fItype\fR may be \fIdir\fR for a hard drive, \fIfloppy\fR for a floppy
drive or \fIcdrom\fR for a cdrom. \fIsize\fR specifies the size of the volume.
You can force ASPI mode for a cdrom with \fB-aspi\fR.
.TP
\fBMEM\fR
Display the amount of free memory
.TP
\fBCONFIG\fR [\fB-writeconf\fR] [\fB-writelang\fR] \fBfile\fR
Write the current configuration or language settings to \fBfile\fR
.SH FILES
Configuration and language files use a format similar to Windows .ini files. If a file named
\fBdosbox.conf\fR is found in the current directory, it will be automatically loaded.
.SH BUGS
Not all DOS programs work properly. Notably, any program that uses protected mode will not work at all.
DOSBox will exit without warning if an error occured.
.SH SEE ALSO
The README in /usr/share/doc/dosbox
.SH AUTHOR
This manual page was written by Peter Veenstra <H.P.Veenstra@student.rug.nl> and James Oakley <jfunk@funktronics.ca>,
for the Debian system (but may be used by others).
