set(mapperfile_files
    xbox/abreed.map
    xbox/abreedta.map
    xbox/actuas.map
    xbox/aitd.map
    xbox/aitd2.map
    xbox/aitd3.map
    xbox/aitdjack.map
    xbox/aladdin.map
    xbox/alienc.map
    xbox/alienr.map
    xbox/alientri.map
    xbox/alphasto.map
    xbox/alqadim.map
    xbox/amok.map
    xbox/another.map
    xbox/batmanac.map
    xbox/batmanf.map
    xbox/bigredr.map
    xbox/blam.map
    xbox/blood.map
    xbox/bluesb.map
    xbox/bluesbja.map
    xbox/bstone.map
    xbox/bstone2.map
    xbox/bthorne.map
    xbox/cadillac.map
    xbox/cataco3d.map
    xbox/catapoc.map
    xbox/chxquest.map
    xbox/cite.map
    xbox/ckeen1.map
    xbox/clifd.map
    xbox/coolspot.map
    xbox/covertac.map
    xbox/crusnreg.map
    xbox/crusnrem.map
    xbox/cyberm.map
    xbox/d.map
    xbox/dderby.map
    xbox/dderby2.map
    xbox/ddragon.map
    xbox/ddragon2.map
    xbox/ddragon3.map
    xbox/descent.map
    xbox/descent2.map
    xbox/disc.map
    xbox/dnukem.map
    xbox/dnukem2.map
    xbox/doom.map
    xbox/doom2.map
    xbox/drally.map
    xbox/dstrike.map
    xbox/duke3d.map
    xbox/ecstatic.map
    xbox/ecstatic2.map
    xbox/eradicat.map
    xbox/ewj.map
    xbox/ewj2.map
    xbox/exhumed.map
    xbox/extremea.map
    xbox/fadetb.map
    xbox/fatalr.map
    xbox/fb.map
    xbox/fifa.map
    xbox/fifa96.map
    xbox/fifa97.map
    xbox/firestrm.map
    xbox/funtrack.map
    xbox/fxfightr.map
    xbox/gb2.map
    xbox/gods.map
    xbox/goldnaxe.map
    xbox/gta.map
    xbox/gtalond.map
    xbox/heretic.map
    xbox/hexen.map
    xbox/hioctane.map
    xbox/horde.map
    xbox/hulkpant.map
    xbox/humans.map
    xbox/jazz.map
    xbox/jbazooka.map
    xbox/jdredd.map
    xbox/jimpower.map
    xbox/joemac.map
    xbox/jstrike.map
    xbox/jungbook.map
    xbox/jurassic.map
    xbox/krusty.map
    xbox/lba.map
    xbox/lba2.map
    xbox/lionking.map
    xbox/lollypop.map
    xbox/lostv.map
    xbox/lostv2.map
    xbox/magicp.map
    xbox/mars3d.map
    xbox/mdk.map
    xbox/megarac2.map
    xbox/megarace.map
    xbox/menace.map
    xbox/microcsm.map
    xbox/mk1.map
    xbox/mk2.map
    xbox/mk3.map
    xbox/mktril.map
    xbox/mm.map
    xbox/mm2.map
    xbox/moktar.map
    xbox/moon.map
    xbox/nba97.map
    xbox/nbajamte.map
    xbox/nfsse.map
    xbox/nhl97.map
    xbox/novas.map
    xbox/oddworld.map
    xbox/omf2097.map
    xbox/panzakb.map
    xbox/petesamp.map
    xbox/pitfghtr.map
    xbox/pop.map
    xbox/pop2.map
    xbox/prayfd.map
    xbox/preh.map
    xbox/preh2.map
    xbox/primrage.map
    xbox/pushover.map
    xbox/quake.map
    xbox/raiden.map
    xbox/rallyc.map
    xbox/raptor.map
    xbox/rayman.map
    xbox/redneck.map
    xbox/redneck2.map
    xbox/reloaded.map
    xbox/rg97.map
    xbox/rise.map
    xbox/rise2.map
    xbox/rott.map
    xbox/scorchdp.map
    xbox/screamr.map
    xbox/screamr2.map
    xbox/sf2.map
    xbox/shadoww.map
    xbox/shells.map
    xbox/simparc.map
    xbox/simpbvs.map
    xbox/skynet.map
    xbox/spacer.map
    xbox/spearod.map
    xbox/speedbl2.map
    xbox/spidey.map
    xbox/srally.map
    xbox/ssf2t.map
    xbox/stargunr.map
    xbox/streetr.map
    xbox/strife.map
    xbox/superc.map
    xbox/swdf.map
    xbox/swiv3d.map
    xbox/tbraider.map
    xbox/term2.map
    xbox/termfs.map
    xbox/timec.map
    xbox/timegate.map
    xbox/timewar.map
    xbox/tmnt.map
    xbox/tmntarc.map
    xbox/tmntman.map
    xbox/trackatk.map
    xbox/turric2.map
    xbox/tvcd.map
    xbox/tyrian.map
    xbox/wacky.map
    xbox/warriors.map
    xbox/wcrew.map
    xbox/whaven.map
    xbox/whaven2.map
    xbox/wilds.map
    xbox/wipeout.map
    xbox/wolf3d.map
    xbox/wrallyf.map
    xbox/wwfarc.map
    xbox/wwfiyh.map
    xbox/xenon2.map
    xbox/xmcota.map
)

list(TRANSFORM mapperfile_files PREPEND "mapperfiles/")