name: Linux builds
on: push
env:
  MAX_WARNINGS_GCC_6_Debug:     378
  MAX_WARNINGS_GCC_6_Release:   661
  MAX_WARNINGS_GCC_7_Debug:     380
  MAX_WARNINGS_GCC_7_Release:   329
  MAX_WARNINGS_GCC_8_Debug:     380
  MAX_WARNINGS_GCC_8_Release:   330
  MAX_WARNINGS_GCC_9_Debug:     403
  MAX_WARNINGS_GCC_9_Release:   358
  MAX_WARNINGS_Clang_7_Debug:   193
  MAX_WARNINGS_Clang_7_Release: 193
  MAX_WARNINGS_Clang_8_Debug:   193
  MAX_WARNINGS_Clang_8_Release: 193

jobs:

  build_matrix:
    name: ${{ matrix.compiler }}-${{ matrix.compiler_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [Clang, GCC]
        compiler_version: [6, 7, 8, 9]
        # build_type: [Debug, Release]
        exclude:
          - compiler: Clang
            compiler_version: 6
          - compiler: Clang
            compiler_version: 9
    steps:
      - uses: actions/checkout@v1
      - run:  sudo apt-get update
      - name: Install C++ compiler and libraries
        run:  sudo apt-get install -y $(./scripts/list-build-dependencies.sh -m apt -c ${{ matrix.compiler }} -v ${{ matrix.compiler_version }})
      - name: Log environment
        run:  ./scripts/log-env.sh
      - name: Release build
        run:  ./scripts/build.sh --compiler ${{ matrix.compiler }} --version-postfix ${{ matrix.compiler_version }} --build-type Release
      - name: Release warnings
        run:  ./scripts/count-warnings.py -m $MAX_WARNINGS_${{ matrix.compiler }}_${{ matrix.compiler_version }}_Release build.log
      - name: Debug build
        run:  ./scripts/build.sh --compiler ${{ matrix.compiler }} --version-postfix ${{ matrix.compiler_version }} --build-type Debug
      - name: Debug warnings
        run:  ./scripts/count-warnings.py -m $MAX_WARNINGS_${{ matrix.compiler }}_${{ matrix.compiler_version }}_Debug build.log
