name: PVS-Studio analysis

on: push

env:
  CCACHE_DIR:      "/dev/shm/.ccache"
  CCACHE_MAXSIZE:  "64M"
  CCACHE_COMPRESS: "true"

jobs:
  pvs_studio_analyzer:
    name: PVS-Studio static analyzer
    runs-on: ubuntu-20.04
    env:
      debfile: pvs-studio-7.11.44138.98-amd64.deb
    steps:
      - uses: actions/checkout@v2
      - run:  sudo apt-get update
      - name: Log and setup environment
        run: |
          ./scripts/log-env.sh
          mkdir -p pvs-package
      - uses: actions/cache@v2
        id: cache-pvs
        with:
          path: pvs-package
          key: ${{ env.debfile }}
      - name:  Fetch PVS-Studio package
        if:    steps.cache-pvs.outputs.cache-hit != 'true'
        run:   wget "https://files.viva64.com/${debfile}" -O "pvs-package/pvs.deb"
      - name: Install packages
        run: |
          set -xeu
          sudo apt-get install strace $(./scripts/list-build-dependencies.sh -m apt -c gcc)
          sudo dpkg -i "pvs-package/pvs.deb"
          pvs-studio-analyzer credentials "${{ secrets.PvsStudioName }}" "${{ secrets.PvsStudioKey }}"
      - name: Build
        run: |
          set -xeu
          ./autogen.sh
          export FLAGS="-Og"
          ./configure CFLAGS="${FLAGS}" CXXFLAGS="${FLAGS}"
          pvs-studio-analyzer trace -- make
      - name: Analyze
        run: |
          set -xeu
          log="pvs-analysis.log"
          general_criteria="GA:1,2;64:1;OP:1,2,3;CS:1"
          stamp="$(date +'%Y-%m-%d_T%H%M')-${GITHUB_SHA:0:8}"
          reportdir="pvs-report/pvs-report-${stamp}"
          disable_warnings="V1042,V826"
          mkdir -p "${reportdir}"
          pvs-studio-analyzer analyze \
            --disableLicenseExpirationCheck \
            -a 63 \
            -s .pvs-suppress \
            -j "$(nproc)" \
            -o "${log}"
          plog-converter \
            -p dosbox-staging \
            -v "${GITHUB_SHA:0:8}" \
            -a "${general_criteria}" \
            -d "${disable_warnings}" \
            -t fullhtml \
            -o "${reportdir}" \
            "${log}"
          mv "${reportdir}/fullhtml" "${reportdir}/general"
          plog-converter \
            -a "${general_criteria}" \
            -d "${disable_warnings}" \
            -t csv \
            -o pvs-report.csv \
            "${log}"
          cp -l pvs-report.csv "${reportdir}/general/"
          pvs-studio-analyzer suppress \
            -a "${general_criteria}" \
            -o "${reportdir}/general/supressible-list.json" \
            "${log}"
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: pvs-analysis-report
          path: pvs-report
      - name: Summarize report
        env:
          MAX_BUGS: 458
        run: |
          echo "Full report is included in build Artifacts"
          echo
          ./scripts/count-pvs-bugs.py pvs-report.csv "${MAX_BUGS}"
