name: Deploy website preview (PR)
permissions: read-all

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'website/**'

jobs:
  deploy:
    if: github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/deploy-website.yml
    with:
      source_branch: ${{ github.event.pull_request.head.ref }}
      destination_prefix: pr-${{ github.event.pull_request.number }}
    secrets: inherit
