name: Update release notes preview
permissions: read-all

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PRE_RELEASE_TAG:   0.83.0-alpha
  GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_RELEASE_DRAFTER }}

jobs:
  update_release_notes:
    runs-on: ubuntu-slim
    if: github.repository == 'dosbox-staging/dosbox-staging'
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          submodules: false

      - name: Set common vars
        uses: ./.github/actions/set-common-vars

      - name: Install markdown2
        shell: bash
        run: pip3 install markdown2 requests

      - name: Query pull requests
        run: |
          ./scripts/tools/release-notes-drafter.py \
              summary.query \
              --start_time            $RELEASE_START_TIME \
              --out_pull_requests_csv pull-requests.csv

      - name: Generate release notes
        run: |
          ./scripts/tools/release-notes-drafter.py \
              summary.process \
              --input_csv_file    pull-requests.csv \
              --out_markdown_file release-notes.md

      - name: Publish release notes preview
        run: |
          ./scripts/tools/release-notes-drafter.py \
              summary.publish \
              --release_notes_file  release-notes.md \
              --publish_version_tag $PRE_RELEASE_TAG

